version: '3'
services:
    app:
        command: gunicorn -t 90 --bind=0.0.0.0 app.api:app --workers=4
        environment:
            - FLASK_CONF=production
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8000:8000"
