# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1
orbs:
    newman: postman/newman@0.0.2
jobs:
  unit_test:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.6

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            virtualenv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - run:
          name: install spacy model
          command: |
            . venv/bin/activate
            python -m spacy download en

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
        
      # run tests!
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            mkdir ~/repo/logs
            pytest tests/

      - store_artifacts:
          path: test-reports
          destination: test-reports

  integration_test:
    executor: newman/postman-newman-docker

    steps:
      - checkout

      - newman/newman-run:
          collection: ./postman_collection.json

workflows:
  version: 2.1
  run_tests:
    jobs:
      - unit_test
      - integration_test
